//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CitasBambuDC.WSBambu {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSBambu.WSDBSoap")]
    public interface WSDBSoap {
        
        // CODEGEN: Generating message contract since element name correo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogIn", ReplyAction="*")]
        CitasBambuDC.WSBambu.LogInResponse LogIn(CitasBambuDC.WSBambu.LogInRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogIn", ReplyAction="*")]
        System.Threading.Tasks.Task<CitasBambuDC.WSBambu.LogInResponse> LogInAsync(CitasBambuDC.WSBambu.LogInRequest request);
        
        // CODEGEN: Generating message contract since element name correo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogOut", ReplyAction="*")]
        CitasBambuDC.WSBambu.LogOutResponse LogOut(CitasBambuDC.WSBambu.LogOutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogOut", ReplyAction="*")]
        System.Threading.Tasks.Task<CitasBambuDC.WSBambu.LogOutResponse> LogOutAsync(CitasBambuDC.WSBambu.LogOutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearCita", ReplyAction="*")]
        bool CrearCita(System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearCita", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> CrearCitaAsync(System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BorrarCita", ReplyAction="*")]
        bool BorrarCita(int idFecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BorrarCita", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> BorrarCitaAsync(int idFecha);
        
        // CODEGEN: Generating message contract since element name correoCliente from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReservarCita", ReplyAction="*")]
        CitasBambuDC.WSBambu.ReservarCitaResponse ReservarCita(CitasBambuDC.WSBambu.ReservarCitaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReservarCita", ReplyAction="*")]
        System.Threading.Tasks.Task<CitasBambuDC.WSBambu.ReservarCitaResponse> ReservarCitaAsync(CitasBambuDC.WSBambu.ReservarCitaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogInRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogIn", Namespace="http://tempuri.org/", Order=0)]
        public CitasBambuDC.WSBambu.LogInRequestBody Body;
        
        public LogInRequest() {
        }
        
        public LogInRequest(CitasBambuDC.WSBambu.LogInRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogInRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string correo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        public LogInRequestBody() {
        }
        
        public LogInRequestBody(string correo, string pass) {
            this.correo = correo;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogInResponse", Namespace="http://tempuri.org/", Order=0)]
        public CitasBambuDC.WSBambu.LogInResponseBody Body;
        
        public LogInResponse() {
        }
        
        public LogInResponse(CitasBambuDC.WSBambu.LogInResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogInResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LogInResult;
        
        public LogInResponseBody() {
        }
        
        public LogInResponseBody(bool LogInResult) {
            this.LogInResult = LogInResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogOutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogOut", Namespace="http://tempuri.org/", Order=0)]
        public CitasBambuDC.WSBambu.LogOutRequestBody Body;
        
        public LogOutRequest() {
        }
        
        public LogOutRequest(CitasBambuDC.WSBambu.LogOutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogOutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string correo;
        
        public LogOutRequestBody() {
        }
        
        public LogOutRequestBody(string correo) {
            this.correo = correo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogOutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogOutResponse", Namespace="http://tempuri.org/", Order=0)]
        public CitasBambuDC.WSBambu.LogOutResponseBody Body;
        
        public LogOutResponse() {
        }
        
        public LogOutResponse(CitasBambuDC.WSBambu.LogOutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogOutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LogOutResult;
        
        public LogOutResponseBody() {
        }
        
        public LogOutResponseBody(bool LogOutResult) {
            this.LogOutResult = LogOutResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReservarCitaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReservarCita", Namespace="http://tempuri.org/", Order=0)]
        public CitasBambuDC.WSBambu.ReservarCitaRequestBody Body;
        
        public ReservarCitaRequest() {
        }
        
        public ReservarCitaRequest(CitasBambuDC.WSBambu.ReservarCitaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReservarCitaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string correoCliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime fecha;
        
        public ReservarCitaRequestBody() {
        }
        
        public ReservarCitaRequestBody(string correoCliente, System.DateTime fecha) {
            this.correoCliente = correoCliente;
            this.fecha = fecha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReservarCitaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReservarCitaResponse", Namespace="http://tempuri.org/", Order=0)]
        public CitasBambuDC.WSBambu.ReservarCitaResponseBody Body;
        
        public ReservarCitaResponse() {
        }
        
        public ReservarCitaResponse(CitasBambuDC.WSBambu.ReservarCitaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReservarCitaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ReservarCitaResult;
        
        public ReservarCitaResponseBody() {
        }
        
        public ReservarCitaResponseBody(bool ReservarCitaResult) {
            this.ReservarCitaResult = ReservarCitaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSDBSoapChannel : CitasBambuDC.WSBambu.WSDBSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSDBSoapClient : System.ServiceModel.ClientBase<CitasBambuDC.WSBambu.WSDBSoap>, CitasBambuDC.WSBambu.WSDBSoap {
        
        public WSDBSoapClient() {
        }
        
        public WSDBSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSDBSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSDBSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSDBSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CitasBambuDC.WSBambu.LogInResponse CitasBambuDC.WSBambu.WSDBSoap.LogIn(CitasBambuDC.WSBambu.LogInRequest request) {
            return base.Channel.LogIn(request);
        }
        
        public bool LogIn(string correo, string pass) {
            CitasBambuDC.WSBambu.LogInRequest inValue = new CitasBambuDC.WSBambu.LogInRequest();
            inValue.Body = new CitasBambuDC.WSBambu.LogInRequestBody();
            inValue.Body.correo = correo;
            inValue.Body.pass = pass;
            CitasBambuDC.WSBambu.LogInResponse retVal = ((CitasBambuDC.WSBambu.WSDBSoap)(this)).LogIn(inValue);
            return retVal.Body.LogInResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CitasBambuDC.WSBambu.LogInResponse> CitasBambuDC.WSBambu.WSDBSoap.LogInAsync(CitasBambuDC.WSBambu.LogInRequest request) {
            return base.Channel.LogInAsync(request);
        }
        
        public System.Threading.Tasks.Task<CitasBambuDC.WSBambu.LogInResponse> LogInAsync(string correo, string pass) {
            CitasBambuDC.WSBambu.LogInRequest inValue = new CitasBambuDC.WSBambu.LogInRequest();
            inValue.Body = new CitasBambuDC.WSBambu.LogInRequestBody();
            inValue.Body.correo = correo;
            inValue.Body.pass = pass;
            return ((CitasBambuDC.WSBambu.WSDBSoap)(this)).LogInAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CitasBambuDC.WSBambu.LogOutResponse CitasBambuDC.WSBambu.WSDBSoap.LogOut(CitasBambuDC.WSBambu.LogOutRequest request) {
            return base.Channel.LogOut(request);
        }
        
        public bool LogOut(string correo) {
            CitasBambuDC.WSBambu.LogOutRequest inValue = new CitasBambuDC.WSBambu.LogOutRequest();
            inValue.Body = new CitasBambuDC.WSBambu.LogOutRequestBody();
            inValue.Body.correo = correo;
            CitasBambuDC.WSBambu.LogOutResponse retVal = ((CitasBambuDC.WSBambu.WSDBSoap)(this)).LogOut(inValue);
            return retVal.Body.LogOutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CitasBambuDC.WSBambu.LogOutResponse> CitasBambuDC.WSBambu.WSDBSoap.LogOutAsync(CitasBambuDC.WSBambu.LogOutRequest request) {
            return base.Channel.LogOutAsync(request);
        }
        
        public System.Threading.Tasks.Task<CitasBambuDC.WSBambu.LogOutResponse> LogOutAsync(string correo) {
            CitasBambuDC.WSBambu.LogOutRequest inValue = new CitasBambuDC.WSBambu.LogOutRequest();
            inValue.Body = new CitasBambuDC.WSBambu.LogOutRequestBody();
            inValue.Body.correo = correo;
            return ((CitasBambuDC.WSBambu.WSDBSoap)(this)).LogOutAsync(inValue);
        }
        
        public bool CrearCita(System.DateTime fecha) {
            return base.Channel.CrearCita(fecha);
        }
        
        public System.Threading.Tasks.Task<bool> CrearCitaAsync(System.DateTime fecha) {
            return base.Channel.CrearCitaAsync(fecha);
        }
        
        public bool BorrarCita(int idFecha) {
            return base.Channel.BorrarCita(idFecha);
        }
        
        public System.Threading.Tasks.Task<bool> BorrarCitaAsync(int idFecha) {
            return base.Channel.BorrarCitaAsync(idFecha);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CitasBambuDC.WSBambu.ReservarCitaResponse CitasBambuDC.WSBambu.WSDBSoap.ReservarCita(CitasBambuDC.WSBambu.ReservarCitaRequest request) {
            return base.Channel.ReservarCita(request);
        }
        
        public bool ReservarCita(string correoCliente, System.DateTime fecha) {
            CitasBambuDC.WSBambu.ReservarCitaRequest inValue = new CitasBambuDC.WSBambu.ReservarCitaRequest();
            inValue.Body = new CitasBambuDC.WSBambu.ReservarCitaRequestBody();
            inValue.Body.correoCliente = correoCliente;
            inValue.Body.fecha = fecha;
            CitasBambuDC.WSBambu.ReservarCitaResponse retVal = ((CitasBambuDC.WSBambu.WSDBSoap)(this)).ReservarCita(inValue);
            return retVal.Body.ReservarCitaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CitasBambuDC.WSBambu.ReservarCitaResponse> CitasBambuDC.WSBambu.WSDBSoap.ReservarCitaAsync(CitasBambuDC.WSBambu.ReservarCitaRequest request) {
            return base.Channel.ReservarCitaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CitasBambuDC.WSBambu.ReservarCitaResponse> ReservarCitaAsync(string correoCliente, System.DateTime fecha) {
            CitasBambuDC.WSBambu.ReservarCitaRequest inValue = new CitasBambuDC.WSBambu.ReservarCitaRequest();
            inValue.Body = new CitasBambuDC.WSBambu.ReservarCitaRequestBody();
            inValue.Body.correoCliente = correoCliente;
            inValue.Body.fecha = fecha;
            return ((CitasBambuDC.WSBambu.WSDBSoap)(this)).ReservarCitaAsync(inValue);
        }
    }
}
