//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CitasBambuDC.BambuWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SerializablePersona", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SerializablePersona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PersonaIDField;
        
        private int CedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimerNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SegundoNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimerApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SegundoApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        private bool EsAdminField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PersonaID {
            get {
                return this.PersonaIDField;
            }
            set {
                if ((this.PersonaIDField.Equals(value) != true)) {
                    this.PersonaIDField = value;
                    this.RaisePropertyChanged("PersonaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((this.CedulaField.Equals(value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PrimerNombre {
            get {
                return this.PrimerNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimerNombreField, value) != true)) {
                    this.PrimerNombreField = value;
                    this.RaisePropertyChanged("PrimerNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SegundoNombre {
            get {
                return this.SegundoNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.SegundoNombreField, value) != true)) {
                    this.SegundoNombreField = value;
                    this.RaisePropertyChanged("SegundoNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PrimerApellido {
            get {
                return this.PrimerApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimerApellidoField, value) != true)) {
                    this.PrimerApellidoField = value;
                    this.RaisePropertyChanged("PrimerApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SegundoApellido {
            get {
                return this.SegundoApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.SegundoApellidoField, value) != true)) {
                    this.SegundoApellidoField = value;
                    this.RaisePropertyChanged("SegundoApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool EsAdmin {
            get {
                return this.EsAdminField;
            }
            set {
                if ((this.EsAdminField.Equals(value) != true)) {
                    this.EsAdminField = value;
                    this.RaisePropertyChanged("EsAdmin");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SerializableCita", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SerializableCita : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CitasIDField;
        
        private System.Nullable<System.DateTime> FechaField;
        
        private System.Nullable<int> ClienteAsignadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CitasID {
            get {
                return this.CitasIDField;
            }
            set {
                if ((this.CitasIDField.Equals(value) != true)) {
                    this.CitasIDField = value;
                    this.RaisePropertyChanged("CitasID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<int> ClienteAsignado {
            get {
                return this.ClienteAsignadoField;
            }
            set {
                if ((this.ClienteAsignadoField.Equals(value) != true)) {
                    this.ClienteAsignadoField = value;
                    this.RaisePropertyChanged("ClienteAsignado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BambuWS.WSDBSoap")]
    public interface WSDBSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento primerNombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearUsuario", ReplyAction="*")]
        CitasBambuDC.BambuWS.CrearUsuarioResponse CrearUsuario(CitasBambuDC.BambuWS.CrearUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<CitasBambuDC.BambuWS.CrearUsuarioResponse> CrearUsuarioAsync(CitasBambuDC.BambuWS.CrearUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento correo del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogIn", ReplyAction="*")]
        CitasBambuDC.BambuWS.LogInResponse LogIn(CitasBambuDC.BambuWS.LogInRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogIn", ReplyAction="*")]
        System.Threading.Tasks.Task<CitasBambuDC.BambuWS.LogInResponse> LogInAsync(CitasBambuDC.BambuWS.LogInRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearCita", ReplyAction="*")]
        bool CrearCita(System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearCita", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> CrearCitaAsync(System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BorrarCita", ReplyAction="*")]
        bool BorrarCita(int idCita);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BorrarCita", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> BorrarCitaAsync(int idCita);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento descripcion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReservarCita", ReplyAction="*")]
        CitasBambuDC.BambuWS.ReservarCitaResponse ReservarCita(CitasBambuDC.BambuWS.ReservarCitaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReservarCita", ReplyAction="*")]
        System.Threading.Tasks.Task<CitasBambuDC.BambuWS.ReservarCitaResponse> ReservarCitaAsync(CitasBambuDC.BambuWS.ReservarCitaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CitasDeClienteResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CitasDeCliente", ReplyAction="*")]
        CitasBambuDC.BambuWS.CitasDeClienteResponse CitasDeCliente(CitasBambuDC.BambuWS.CitasDeClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CitasDeCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<CitasBambuDC.BambuWS.CitasDeClienteResponse> CitasDeClienteAsync(CitasBambuDC.BambuWS.CitasDeClienteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListaDeCitasResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaDeCitas", ReplyAction="*")]
        CitasBambuDC.BambuWS.ListaDeCitasResponse ListaDeCitas(CitasBambuDC.BambuWS.ListaDeCitasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaDeCitas", ReplyAction="*")]
        System.Threading.Tasks.Task<CitasBambuDC.BambuWS.ListaDeCitasResponse> ListaDeCitasAsync(CitasBambuDC.BambuWS.ListaDeCitasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento InfoPersonaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InfoPersona", ReplyAction="*")]
        CitasBambuDC.BambuWS.InfoPersonaResponse InfoPersona(CitasBambuDC.BambuWS.InfoPersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InfoPersona", ReplyAction="*")]
        System.Threading.Tasks.Task<CitasBambuDC.BambuWS.InfoPersonaResponse> InfoPersonaAsync(CitasBambuDC.BambuWS.InfoPersonaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearUsuario", Namespace="http://tempuri.org/", Order=0)]
        public CitasBambuDC.BambuWS.CrearUsuarioRequestBody Body;
        
        public CrearUsuarioRequest() {
        }
        
        public CrearUsuarioRequest(CitasBambuDC.BambuWS.CrearUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrearUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int cedula;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string primerNombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string segundoNombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string primerApellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string segundoApellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string telefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string correo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string password;
        
        public CrearUsuarioRequestBody() {
        }
        
        public CrearUsuarioRequestBody(int cedula, string primerNombre, string segundoNombre, string primerApellido, string segundoApellido, string telefono, string correo, string password) {
            this.cedula = cedula;
            this.primerNombre = primerNombre;
            this.segundoNombre = segundoNombre;
            this.primerApellido = primerApellido;
            this.segundoApellido = segundoApellido;
            this.telefono = telefono;
            this.correo = correo;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public CitasBambuDC.BambuWS.CrearUsuarioResponseBody Body;
        
        public CrearUsuarioResponse() {
        }
        
        public CrearUsuarioResponse(CitasBambuDC.BambuWS.CrearUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrearUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CrearUsuarioResult;
        
        public CrearUsuarioResponseBody() {
        }
        
        public CrearUsuarioResponseBody(bool CrearUsuarioResult) {
            this.CrearUsuarioResult = CrearUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogInRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogIn", Namespace="http://tempuri.org/", Order=0)]
        public CitasBambuDC.BambuWS.LogInRequestBody Body;
        
        public LogInRequest() {
        }
        
        public LogInRequest(CitasBambuDC.BambuWS.LogInRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogInRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string correo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        public LogInRequestBody() {
        }
        
        public LogInRequestBody(string correo, string pass) {
            this.correo = correo;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogInResponse", Namespace="http://tempuri.org/", Order=0)]
        public CitasBambuDC.BambuWS.LogInResponseBody Body;
        
        public LogInResponse() {
        }
        
        public LogInResponse(CitasBambuDC.BambuWS.LogInResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogInResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CitasBambuDC.BambuWS.SerializablePersona LogInResult;
        
        public LogInResponseBody() {
        }
        
        public LogInResponseBody(CitasBambuDC.BambuWS.SerializablePersona LogInResult) {
            this.LogInResult = LogInResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReservarCitaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReservarCita", Namespace="http://tempuri.org/", Order=0)]
        public CitasBambuDC.BambuWS.ReservarCitaRequestBody Body;
        
        public ReservarCitaRequest() {
        }
        
        public ReservarCitaRequest(CitasBambuDC.BambuWS.ReservarCitaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReservarCitaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int cedulaCliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int idCita;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string descripcion;
        
        public ReservarCitaRequestBody() {
        }
        
        public ReservarCitaRequestBody(int cedulaCliente, int idCita, string descripcion) {
            this.cedulaCliente = cedulaCliente;
            this.idCita = idCita;
            this.descripcion = descripcion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReservarCitaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReservarCitaResponse", Namespace="http://tempuri.org/", Order=0)]
        public CitasBambuDC.BambuWS.ReservarCitaResponseBody Body;
        
        public ReservarCitaResponse() {
        }
        
        public ReservarCitaResponse(CitasBambuDC.BambuWS.ReservarCitaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReservarCitaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ReservarCitaResult;
        
        public ReservarCitaResponseBody() {
        }
        
        public ReservarCitaResponseBody(bool ReservarCitaResult) {
            this.ReservarCitaResult = ReservarCitaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CitasDeClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CitasDeCliente", Namespace="http://tempuri.org/", Order=0)]
        public CitasBambuDC.BambuWS.CitasDeClienteRequestBody Body;
        
        public CitasDeClienteRequest() {
        }
        
        public CitasDeClienteRequest(CitasBambuDC.BambuWS.CitasDeClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CitasDeClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int cedula;
        
        public CitasDeClienteRequestBody() {
        }
        
        public CitasDeClienteRequestBody(int cedula) {
            this.cedula = cedula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CitasDeClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CitasDeClienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public CitasBambuDC.BambuWS.CitasDeClienteResponseBody Body;
        
        public CitasDeClienteResponse() {
        }
        
        public CitasDeClienteResponse(CitasBambuDC.BambuWS.CitasDeClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CitasDeClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CitasBambuDC.BambuWS.SerializableCita[] CitasDeClienteResult;
        
        public CitasDeClienteResponseBody() {
        }
        
        public CitasDeClienteResponseBody(CitasBambuDC.BambuWS.SerializableCita[] CitasDeClienteResult) {
            this.CitasDeClienteResult = CitasDeClienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaDeCitasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaDeCitas", Namespace="http://tempuri.org/", Order=0)]
        public CitasBambuDC.BambuWS.ListaDeCitasRequestBody Body;
        
        public ListaDeCitasRequest() {
        }
        
        public ListaDeCitasRequest(CitasBambuDC.BambuWS.ListaDeCitasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListaDeCitasRequestBody {
        
        public ListaDeCitasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaDeCitasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaDeCitasResponse", Namespace="http://tempuri.org/", Order=0)]
        public CitasBambuDC.BambuWS.ListaDeCitasResponseBody Body;
        
        public ListaDeCitasResponse() {
        }
        
        public ListaDeCitasResponse(CitasBambuDC.BambuWS.ListaDeCitasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaDeCitasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CitasBambuDC.BambuWS.SerializableCita[] ListaDeCitasResult;
        
        public ListaDeCitasResponseBody() {
        }
        
        public ListaDeCitasResponseBody(CitasBambuDC.BambuWS.SerializableCita[] ListaDeCitasResult) {
            this.ListaDeCitasResult = ListaDeCitasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InfoPersonaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InfoPersona", Namespace="http://tempuri.org/", Order=0)]
        public CitasBambuDC.BambuWS.InfoPersonaRequestBody Body;
        
        public InfoPersonaRequest() {
        }
        
        public InfoPersonaRequest(CitasBambuDC.BambuWS.InfoPersonaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InfoPersonaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int cedula;
        
        public InfoPersonaRequestBody() {
        }
        
        public InfoPersonaRequestBody(int cedula) {
            this.cedula = cedula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InfoPersonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InfoPersonaResponse", Namespace="http://tempuri.org/", Order=0)]
        public CitasBambuDC.BambuWS.InfoPersonaResponseBody Body;
        
        public InfoPersonaResponse() {
        }
        
        public InfoPersonaResponse(CitasBambuDC.BambuWS.InfoPersonaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InfoPersonaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CitasBambuDC.BambuWS.SerializablePersona InfoPersonaResult;
        
        public InfoPersonaResponseBody() {
        }
        
        public InfoPersonaResponseBody(CitasBambuDC.BambuWS.SerializablePersona InfoPersonaResult) {
            this.InfoPersonaResult = InfoPersonaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSDBSoapChannel : CitasBambuDC.BambuWS.WSDBSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSDBSoapClient : System.ServiceModel.ClientBase<CitasBambuDC.BambuWS.WSDBSoap>, CitasBambuDC.BambuWS.WSDBSoap {
        
        public WSDBSoapClient() {
        }
        
        public WSDBSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSDBSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSDBSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSDBSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CitasBambuDC.BambuWS.CrearUsuarioResponse CitasBambuDC.BambuWS.WSDBSoap.CrearUsuario(CitasBambuDC.BambuWS.CrearUsuarioRequest request) {
            return base.Channel.CrearUsuario(request);
        }
        
        public bool CrearUsuario(int cedula, string primerNombre, string segundoNombre, string primerApellido, string segundoApellido, string telefono, string correo, string password) {
            CitasBambuDC.BambuWS.CrearUsuarioRequest inValue = new CitasBambuDC.BambuWS.CrearUsuarioRequest();
            inValue.Body = new CitasBambuDC.BambuWS.CrearUsuarioRequestBody();
            inValue.Body.cedula = cedula;
            inValue.Body.primerNombre = primerNombre;
            inValue.Body.segundoNombre = segundoNombre;
            inValue.Body.primerApellido = primerApellido;
            inValue.Body.segundoApellido = segundoApellido;
            inValue.Body.telefono = telefono;
            inValue.Body.correo = correo;
            inValue.Body.password = password;
            CitasBambuDC.BambuWS.CrearUsuarioResponse retVal = ((CitasBambuDC.BambuWS.WSDBSoap)(this)).CrearUsuario(inValue);
            return retVal.Body.CrearUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CitasBambuDC.BambuWS.CrearUsuarioResponse> CitasBambuDC.BambuWS.WSDBSoap.CrearUsuarioAsync(CitasBambuDC.BambuWS.CrearUsuarioRequest request) {
            return base.Channel.CrearUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<CitasBambuDC.BambuWS.CrearUsuarioResponse> CrearUsuarioAsync(int cedula, string primerNombre, string segundoNombre, string primerApellido, string segundoApellido, string telefono, string correo, string password) {
            CitasBambuDC.BambuWS.CrearUsuarioRequest inValue = new CitasBambuDC.BambuWS.CrearUsuarioRequest();
            inValue.Body = new CitasBambuDC.BambuWS.CrearUsuarioRequestBody();
            inValue.Body.cedula = cedula;
            inValue.Body.primerNombre = primerNombre;
            inValue.Body.segundoNombre = segundoNombre;
            inValue.Body.primerApellido = primerApellido;
            inValue.Body.segundoApellido = segundoApellido;
            inValue.Body.telefono = telefono;
            inValue.Body.correo = correo;
            inValue.Body.password = password;
            return ((CitasBambuDC.BambuWS.WSDBSoap)(this)).CrearUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CitasBambuDC.BambuWS.LogInResponse CitasBambuDC.BambuWS.WSDBSoap.LogIn(CitasBambuDC.BambuWS.LogInRequest request) {
            return base.Channel.LogIn(request);
        }
        
        public CitasBambuDC.BambuWS.SerializablePersona LogIn(string correo, string pass) {
            CitasBambuDC.BambuWS.LogInRequest inValue = new CitasBambuDC.BambuWS.LogInRequest();
            inValue.Body = new CitasBambuDC.BambuWS.LogInRequestBody();
            inValue.Body.correo = correo;
            inValue.Body.pass = pass;
            CitasBambuDC.BambuWS.LogInResponse retVal = ((CitasBambuDC.BambuWS.WSDBSoap)(this)).LogIn(inValue);
            return retVal.Body.LogInResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CitasBambuDC.BambuWS.LogInResponse> CitasBambuDC.BambuWS.WSDBSoap.LogInAsync(CitasBambuDC.BambuWS.LogInRequest request) {
            return base.Channel.LogInAsync(request);
        }
        
        public System.Threading.Tasks.Task<CitasBambuDC.BambuWS.LogInResponse> LogInAsync(string correo, string pass) {
            CitasBambuDC.BambuWS.LogInRequest inValue = new CitasBambuDC.BambuWS.LogInRequest();
            inValue.Body = new CitasBambuDC.BambuWS.LogInRequestBody();
            inValue.Body.correo = correo;
            inValue.Body.pass = pass;
            return ((CitasBambuDC.BambuWS.WSDBSoap)(this)).LogInAsync(inValue);
        }
        
        public bool CrearCita(System.DateTime fecha) {
            return base.Channel.CrearCita(fecha);
        }
        
        public System.Threading.Tasks.Task<bool> CrearCitaAsync(System.DateTime fecha) {
            return base.Channel.CrearCitaAsync(fecha);
        }
        
        public bool BorrarCita(int idCita) {
            return base.Channel.BorrarCita(idCita);
        }
        
        public System.Threading.Tasks.Task<bool> BorrarCitaAsync(int idCita) {
            return base.Channel.BorrarCitaAsync(idCita);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CitasBambuDC.BambuWS.ReservarCitaResponse CitasBambuDC.BambuWS.WSDBSoap.ReservarCita(CitasBambuDC.BambuWS.ReservarCitaRequest request) {
            return base.Channel.ReservarCita(request);
        }
        
        public bool ReservarCita(int cedulaCliente, int idCita, string descripcion) {
            CitasBambuDC.BambuWS.ReservarCitaRequest inValue = new CitasBambuDC.BambuWS.ReservarCitaRequest();
            inValue.Body = new CitasBambuDC.BambuWS.ReservarCitaRequestBody();
            inValue.Body.cedulaCliente = cedulaCliente;
            inValue.Body.idCita = idCita;
            inValue.Body.descripcion = descripcion;
            CitasBambuDC.BambuWS.ReservarCitaResponse retVal = ((CitasBambuDC.BambuWS.WSDBSoap)(this)).ReservarCita(inValue);
            return retVal.Body.ReservarCitaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CitasBambuDC.BambuWS.ReservarCitaResponse> CitasBambuDC.BambuWS.WSDBSoap.ReservarCitaAsync(CitasBambuDC.BambuWS.ReservarCitaRequest request) {
            return base.Channel.ReservarCitaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CitasBambuDC.BambuWS.ReservarCitaResponse> ReservarCitaAsync(int cedulaCliente, int idCita, string descripcion) {
            CitasBambuDC.BambuWS.ReservarCitaRequest inValue = new CitasBambuDC.BambuWS.ReservarCitaRequest();
            inValue.Body = new CitasBambuDC.BambuWS.ReservarCitaRequestBody();
            inValue.Body.cedulaCliente = cedulaCliente;
            inValue.Body.idCita = idCita;
            inValue.Body.descripcion = descripcion;
            return ((CitasBambuDC.BambuWS.WSDBSoap)(this)).ReservarCitaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CitasBambuDC.BambuWS.CitasDeClienteResponse CitasBambuDC.BambuWS.WSDBSoap.CitasDeCliente(CitasBambuDC.BambuWS.CitasDeClienteRequest request) {
            return base.Channel.CitasDeCliente(request);
        }
        
        public CitasBambuDC.BambuWS.SerializableCita[] CitasDeCliente(int cedula) {
            CitasBambuDC.BambuWS.CitasDeClienteRequest inValue = new CitasBambuDC.BambuWS.CitasDeClienteRequest();
            inValue.Body = new CitasBambuDC.BambuWS.CitasDeClienteRequestBody();
            inValue.Body.cedula = cedula;
            CitasBambuDC.BambuWS.CitasDeClienteResponse retVal = ((CitasBambuDC.BambuWS.WSDBSoap)(this)).CitasDeCliente(inValue);
            return retVal.Body.CitasDeClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CitasBambuDC.BambuWS.CitasDeClienteResponse> CitasBambuDC.BambuWS.WSDBSoap.CitasDeClienteAsync(CitasBambuDC.BambuWS.CitasDeClienteRequest request) {
            return base.Channel.CitasDeClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<CitasBambuDC.BambuWS.CitasDeClienteResponse> CitasDeClienteAsync(int cedula) {
            CitasBambuDC.BambuWS.CitasDeClienteRequest inValue = new CitasBambuDC.BambuWS.CitasDeClienteRequest();
            inValue.Body = new CitasBambuDC.BambuWS.CitasDeClienteRequestBody();
            inValue.Body.cedula = cedula;
            return ((CitasBambuDC.BambuWS.WSDBSoap)(this)).CitasDeClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CitasBambuDC.BambuWS.ListaDeCitasResponse CitasBambuDC.BambuWS.WSDBSoap.ListaDeCitas(CitasBambuDC.BambuWS.ListaDeCitasRequest request) {
            return base.Channel.ListaDeCitas(request);
        }
        
        public CitasBambuDC.BambuWS.SerializableCita[] ListaDeCitas() {
            CitasBambuDC.BambuWS.ListaDeCitasRequest inValue = new CitasBambuDC.BambuWS.ListaDeCitasRequest();
            inValue.Body = new CitasBambuDC.BambuWS.ListaDeCitasRequestBody();
            CitasBambuDC.BambuWS.ListaDeCitasResponse retVal = ((CitasBambuDC.BambuWS.WSDBSoap)(this)).ListaDeCitas(inValue);
            return retVal.Body.ListaDeCitasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CitasBambuDC.BambuWS.ListaDeCitasResponse> CitasBambuDC.BambuWS.WSDBSoap.ListaDeCitasAsync(CitasBambuDC.BambuWS.ListaDeCitasRequest request) {
            return base.Channel.ListaDeCitasAsync(request);
        }
        
        public System.Threading.Tasks.Task<CitasBambuDC.BambuWS.ListaDeCitasResponse> ListaDeCitasAsync() {
            CitasBambuDC.BambuWS.ListaDeCitasRequest inValue = new CitasBambuDC.BambuWS.ListaDeCitasRequest();
            inValue.Body = new CitasBambuDC.BambuWS.ListaDeCitasRequestBody();
            return ((CitasBambuDC.BambuWS.WSDBSoap)(this)).ListaDeCitasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CitasBambuDC.BambuWS.InfoPersonaResponse CitasBambuDC.BambuWS.WSDBSoap.InfoPersona(CitasBambuDC.BambuWS.InfoPersonaRequest request) {
            return base.Channel.InfoPersona(request);
        }
        
        public CitasBambuDC.BambuWS.SerializablePersona InfoPersona(int cedula) {
            CitasBambuDC.BambuWS.InfoPersonaRequest inValue = new CitasBambuDC.BambuWS.InfoPersonaRequest();
            inValue.Body = new CitasBambuDC.BambuWS.InfoPersonaRequestBody();
            inValue.Body.cedula = cedula;
            CitasBambuDC.BambuWS.InfoPersonaResponse retVal = ((CitasBambuDC.BambuWS.WSDBSoap)(this)).InfoPersona(inValue);
            return retVal.Body.InfoPersonaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CitasBambuDC.BambuWS.InfoPersonaResponse> CitasBambuDC.BambuWS.WSDBSoap.InfoPersonaAsync(CitasBambuDC.BambuWS.InfoPersonaRequest request) {
            return base.Channel.InfoPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CitasBambuDC.BambuWS.InfoPersonaResponse> InfoPersonaAsync(int cedula) {
            CitasBambuDC.BambuWS.InfoPersonaRequest inValue = new CitasBambuDC.BambuWS.InfoPersonaRequest();
            inValue.Body = new CitasBambuDC.BambuWS.InfoPersonaRequestBody();
            inValue.Body.cedula = cedula;
            return ((CitasBambuDC.BambuWS.WSDBSoap)(this)).InfoPersonaAsync(inValue);
        }
    }
}
